# Generated by Django 5.0.6 on 2024-08-24 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Connection_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(max_length=30, verbose_name='Tipo de Conexión')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Conexión',
                'verbose_name_plural': 'Tipos de Conexiónes',
                'db_table': 'tipo_de_conexion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.CharField(max_length=75, verbose_name='Dependencia')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'dependencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dev_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_status', models.CharField(max_length=33, verbose_name='Estado del Dispositivo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Estado del Dispositivo',
                'verbose_name_plural': 'Estados de los Dispositivos',
                'db_table': 'estado_del_dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dev_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=50, verbose_name='Tipo de Dispositivo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
                'db_table': 'tipo_de_dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35, verbose_name='Estado Empleado')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Estado Empleado',
                'verbose_name_plural': 'Estados de Empleados',
                'db_table': 'estados_empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=75, verbose_name='Localidad')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Move_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(max_length=35, verbose_name='Movimiento')),
                ('details', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle Movimiento')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos Movimientos',
                'db_table': 'tipo_movimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patchera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(max_length=2, verbose_name='Patchera')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Patchera',
                'verbose_name_plural': 'Patcheras',
                'db_table': 'patchs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(max_length=2, unique=True, verbose_name='Numero de Distrito')),
                ('province', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Provincia')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.CharField(max_length=6, verbose_name='Rack')),
                ('details', models.TextField(verbose_name='Detalle')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Rack ',
                'verbose_name_plural': 'Racks',
                'db_table': 'rack',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suply_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suply_type', models.CharField(max_length=20, verbose_name='Tipo de Insumo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Insumo',
                'verbose_name_plural': 'Tipos de Insumos',
                'db_table': 'tipos_insumos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=75, verbose_name='Apellido')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dev_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_models/%Y/%m/%d', verbose_name='Imagen')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_brand', to='sh.brand', verbose_name='Marca')),
                ('dev_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_dev_type', to='sh.dev_type', verbose_name='Tipo de Dispositivo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edifice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edifice', models.CharField(max_length=50, verbose_name='Edificio')),
                ('address', models.TextField(verbose_name='Domicilio')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh.location', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'edificios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=50, verbose_name='Oficina')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices_dependencies', to='sh.dependency', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Officina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'oficina',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='Nombre del Empleado')),
                ('employee_last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cuil', models.CharField(max_length=11, verbose_name='cuil')),
                ('user_pc', models.CharField(max_length=11, verbose_name='Nombre de Usuario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img_avatars/%Y/%m/%d', verbose_name='Avatar')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_status', to='sh.employee_status', verbose_name='Estado')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_office', to='sh.office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Office_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=2, verbose_name='Piso')),
                ('wing', models.CharField(max_length=50, verbose_name='Ala')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('edifice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_loc_edifice', to='sh.edifice', verbose_name='Edificio')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_location', to='sh.office_loc', verbose_name='Piso/Ala'),
        ),
        migrations.CreateModel(
            name='Patch_Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=2, verbose_name='Puerto')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patchera_port', to='sh.patchera', verbose_name='Patchera')),
            ],
            options={
                'verbose_name': 'Puerto Patchera',
                'verbose_name_plural': 'Puertos Patcheras',
                'db_table': 'patchs_ports',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh.province', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='patchera',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patchera_rack', to='sh.rack', verbose_name='Rack'),
        ),
        migrations.CreateModel(
            name='Suply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_suply', models.CharField(max_length=25, verbose_name='Número de Serie')),
                ('date_in', models.DateField(verbose_name='Fecha de Ingreso')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('dev_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suply_dev_model', to='sh.dev_model', verbose_name='Modelo de Dispositivo')),
                ('suply_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suply_suply_type', to='sh.suply_type', verbose_name='Tipo de Insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de Serie')),
                ('ports_q', models.CharField(max_length=2, verbose_name='Cantidad de Puertos')),
                ('switch_rack_pos', models.CharField(blank=True, max_length=2, null=True, verbose_name='Posición en el Rack')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_brand', to='sh.brand', verbose_name='Marca')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_office', to='sh.office', verbose_name='Oficina')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_rack', to='sh.rack', verbose_name='Rack')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'db_table': 'switchs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Switch_Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=3, verbose_name='Puerto del Switch')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('patch_port_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_patch_port_in', to='sh.patch_port', verbose_name='Puerto Patchera Entrada')),
                ('patch_port_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_patch_port_out', to='sh.patch_port', verbose_name='Puerto Patchera Salida')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports_switch', to='sh.switch', verbose_name='Switch')),
                ('switch_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports_switch_in', to='sh.switch', verbose_name='Switch de Ingreso')),
                ('switch_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports_switch_out', to='sh.switch', verbose_name='Switch de Salida')),
            ],
            options={
                'verbose_name': 'Puerto de Switch',
                'verbose_name_plural': 'Puertos de Switchs',
                'db_table': 'puertos_switchs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP')),
                ('serial_n', models.CharField(max_length=20, verbose_name='S/N°')),
                ('net_name', models.CharField(blank=True, max_length=11, null=True, verbose_name='ID en la Red')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_connection', to='sh.connection_type', verbose_name='Conexion del Dispositivo')),
                ('dev_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_model', to='sh.dev_model', verbose_name='Modelo de Dispositivo')),
                ('dev_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='sh.dev_status', verbose_name='Estado del Dispositivo')),
                ('employee', models.ManyToManyField(related_name='device_employee', to='sh.employee', verbose_name='Empleado')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_office', to='sh.office', verbose_name='Oficina')),
                ('switch_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_switch_port', to='sh.switch_port', verbose_name='Puerto de Switch')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de realización')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_device', to='sh.device', verbose_name='Dispositivo')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_move_type', to='sh.move_type', verbose_name='Movimiento')),
                ('suply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_suply', to='sh.suply', verbose_name='Insumo')),
                ('techs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_techs', to='sh.techs', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wall_Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_port', models.CharField(max_length=8, verbose_name='Boca Pared')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_wall_port', to='sh.office', verbose_name='Oficina')),
                ('switch_port_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_switch_port_in', to='sh.switch_port', verbose_name='Puerto del Switch Padre')),
                ('switch_port_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_switch_port_out', to='sh.switch_port', verbose_name='Switch Hijo')),
            ],
            options={
                'verbose_name': 'Boca Pared',
                'verbose_name_plural': 'Bocas Pared',
                'db_table': 'wall_port',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='wall_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_wall_port', to='sh.wall_port', verbose_name='Boca de la pared'),
        ),
    ]
