# Generated by Django 5.0.6 on 2024-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move_type',
            name='details',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle Movimiento'),
        ),
        migrations.AlterField(
            model_name='move_type',
            name='move',
            field=models.CharField(max_length=35, verbose_name='Movimiento'),
        ),
    ]
