# Generated by Django 5.0.6 on 2024-11-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rack_office', to='sh.office', verbose_name='oficina'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='move_type',
            constraint=models.UniqueConstraint(fields=('move', 'details'), name='unique_move_details'),
        ),
        migrations.AddConstraint(
            model_name='suply',
            constraint=models.UniqueConstraint(fields=('suply_type', 'dev_model', 'serial_suply'), name='unique_type_model_serial'),
        ),
    ]
