# Generated by Django 5.0.6 on 2024-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suply_type',
            name='suply_type',
            field=models.CharField(max_length=23, unique=True, verbose_name='Tipo de Insumo'),
        ),
    ]
