# Generated by Django 5.0.6 on 2024-08-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='net_name',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='ID en la Red'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_n',
            field=models.CharField(max_length=20, unique=True, verbose_name='S/N°'),
        ),
        migrations.AlterField(
            model_name='device',
            name='switch_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_switch_port', to='sh.switch_port', verbose_name='Puerto de Switch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='wall_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_wall_port', to='sh.wall_port', verbose_name='Boca de la pared'),
        ),
    ]
