# Generated by Django 5.0.6 on 2024-08-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_alter_device_ip_alter_device_net_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='serial_n',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° de Serie'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_rack_pos',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Posición en el Rack'),
        ),
        migrations.AlterField(
            model_name='switch_port',
            name='port_id',
            field=models.CharField(max_length=3, unique=True, verbose_name='Puerto del Switch'),
        ),
    ]
