# Generated by Django 5.0.6 on 2024-12-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_alter_suply_type_suply_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='office',
            name='unique_loc_dependency',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('cuil', 'office'), name='unique_cuil_office'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('office', 'dependency'), name='unique_office_dependency'),
        ),
    ]
