# Generated by Django 5.0.6 on 2024-08-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_move_type_details_alter_move_type_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='description',
            new_name='dependency',
        ),
    ]
