# Generated by Django 5.0.6 on 2024-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0003_rename_description_dependency_dependency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_status',
            options={'ordering': ['id'], 'verbose_name': 'Estado Empleado', 'verbose_name_plural': 'Estados de Empleados'},
        ),
        migrations.AlterField(
            model_name='employee_status',
            name='status',
            field=models.CharField(max_length=35, verbose_name='Estado Empleado'),
        ),
        migrations.AlterModelTable(
            name='employee_status',
            table='estados_empleados',
        ),
    ]
