# Generated by Django 5.0.6 on 2024-08-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0003_alter_switch_serial_n_alter_switch_switch_rack_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_connection', to='sh.connection_type', verbose_name='Conexion del Dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='device_employee', to='sh.employee', verbose_name='Empleado'),
        ),
    ]
