# Generated by Django 5.0.6 on 2024-12-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0003_remove_office_unique_loc_dependency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rack'),
        ),
    ]
