# Generated by Django 5.0.6 on 2024-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0004_alter_device_connection_alter_device_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='edifice',
            name='edifice',
            field=models.CharField(max_length=50, unique=True, verbose_name='Edificio'),
        ),
    ]
