# Generated by Django 5.0.6 on 2024-09-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0007_alter_dependency_dependency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office_loc',
            options={'ordering': ['id'], 'verbose_name': 'Locación de Oficina', 'verbose_name_plural': 'Locaciones de Oficinas'},
        ),
        migrations.AlterModelTable(
            name='office_loc',
            table='locaciones_oficinas',
        ),
    ]
