# Generated by Django 5.0.6 on 2024-09-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0009_alter_office_options_dependency_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='edifice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sh.edifice', verbose_name='Edificio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('location', 'dependency')},
        ),
    ]
