# Generated by Django 5.0.6 on 2024-09-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0011_alter_dev_type_dev_type_alter_rack_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='brand',
        ),
        migrations.AddField(
            model_name='switch',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='switch_model', to='sh.dev_model', verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
