# Generated by Django 5.0.6 on 2024-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0012_remove_switch_brand_switch_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='serial_n',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de Serie'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_rack_pos',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Posición en el Rack'),
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together={('model', 'serial_n')},
        ),
    ]
