# Generated by Django 5.0.6 on 2024-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0013_alter_switch_serial_n_alter_switch_switch_rack_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
    ]
