# Generated by Django 5.0.6 on 2024-09-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0014_alter_switch_date_creation_alter_switch_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edifice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edifice_location', to='sh.location', verbose_name='Localidad'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('province', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together={('rack', 'switch_rack_pos')},
        ),
    ]
