# Generated by Django 5.0.6 on 2024-09-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0015_alter_edifice_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='location',
        ),
    ]
