# Generated by Django 5.0.6 on 2024-09-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0016_alter_dependency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='dependency',
            field=models.CharField(max_length=75, verbose_name='Dependencia'),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('edifice', 'dependency')},
        ),
    ]
