# Generated by Django 5.0.6 on 2024-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0017_alter_dependency_dependency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='dependency',
            field=models.CharField(max_length=75, unique=True, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office',
            field=models.CharField(max_length=75, verbose_name='Oficina'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('loc', 'dependency'), name='unique_loc_dependency'),
        ),
        migrations.AddConstraint(
            model_name='office_loc',
            constraint=models.UniqueConstraint(fields=('edifice', 'floor', 'wing'), name='unique_edifice_floor_wing'),
        ),
    ]
