# Generated by Django 5.0.6 on 2024-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0019_dev_model_unique_dev_type_brand_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='dependency',
            field=models.CharField(max_length=75, verbose_name='Dependencia'),
        ),
    ]
