# Generated by Django 5.0.6 on 2024-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0020_alter_dependency_dependency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edifice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='edifice',
            constraint=models.UniqueConstraint(fields=('edifice', 'location'), name='unique_edifice_location'),
        ),
        migrations.AddConstraint(
            model_name='switch',
            constraint=models.UniqueConstraint(fields=('model', 'serial_n'), name='unique_model_serial'),
        ),
        migrations.AddConstraint(
            model_name='switch',
            constraint=models.UniqueConstraint(fields=('rack', 'switch_rack_pos'), name='unique_rack_switch_rack_pos'),
        ),
    ]
