# Generated by Django 5.0.6 on 2024-10-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0021_alter_edifice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suply_type',
            name='suply_type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tipo de Insumo'),
        ),
    ]
