# Generated by Django 5.0.6 on 2024-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0022_alter_suply_type_suply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_status',
            name='status',
            field=models.CharField(max_length=35, unique=True, verbose_name='Estado Empleado'),
        ),
    ]
