# Generated by Django 5.0.6 on 2024-10-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0023_alter_employee_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cuil',
            field=models.CharField(max_length=11, unique=True, verbose_name='cuil'),
        ),
    ]
