# Generated by Django 5.0.6 on 2024-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0024_alter_employee_cuil'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='techs',
            constraint=models.UniqueConstraint(fields=('name', 'last_name'), name='unique_tech_name'),
        ),
    ]
