# Generated by Django 5.0.6 on 2024-11-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0025_techs_unique_tech_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wall_port',
            options={'ordering': ['id'], 'verbose_name': 'Boca de Pared', 'verbose_name_plural': 'Bocas de Pared'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='switch_port',
            new_name='switch_port_in',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='wall_port',
            new_name='wall_port_in',
        ),
        migrations.RenameField(
            model_name='patch_port',
            old_name='patch',
            new_name='patchera',
        ),
        migrations.RenameField(
            model_name='patchera',
            old_name='patch',
            new_name='patchera',
        ),
        migrations.RemoveField(
            model_name='switch_port',
            name='patch_port_in',
        ),
        migrations.RemoveField(
            model_name='switch_port',
            name='patch_port_out',
        ),
        migrations.RemoveField(
            model_name='switch_port',
            name='switch_in',
        ),
        migrations.RemoveField(
            model_name='switch_port',
            name='switch_out',
        ),
        migrations.RemoveField(
            model_name='wall_port',
            name='switch_port_out',
        ),
        migrations.AddField(
            model_name='device',
            name='patch_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_patch_port', to='sh.patch_port', verbose_name='Puerto de patchera de Entrada'),
        ),
        migrations.AddField(
            model_name='patch_port',
            name='switch_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_port_switch_port_in', to='sh.switch_port', verbose_name='Puerto de Switch'),
        ),
        migrations.AddField(
            model_name='switch',
            name='patch_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_patch_port_in', to='sh.patch_port', verbose_name='Puerto de patchera de Entrada'),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_switch_port_in', to='sh.switch_port', verbose_name='Puerto de Switch'),
        ),
        migrations.AddField(
            model_name='switch',
            name='wall_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_wall_port_in', to='sh.wall_port', verbose_name='Boca de la pared'),
        ),
        migrations.AddField(
            model_name='wall_port',
            name='patch_port_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_patch_port_in', to='sh.patch_port', verbose_name='Puerto de patchera de Entrada'),
        ),
        migrations.AlterField(
            model_name='switch_port',
            name='port_id',
            field=models.CharField(max_length=3, verbose_name='Puerto del Switch'),
        ),
        migrations.AddConstraint(
            model_name='patch_port',
            constraint=models.UniqueConstraint(fields=('patchera', 'port'), name='unique_patchera_port'),
        ),
        migrations.AddConstraint(
            model_name='patchera',
            constraint=models.UniqueConstraint(fields=('rack', 'patchera'), name='unique_rack_patchera'),
        ),
        migrations.AddConstraint(
            model_name='switch_port',
            constraint=models.UniqueConstraint(fields=('switch', 'port_id'), name='unique_switch_port_id'),
        ),
        migrations.AddConstraint(
            model_name='wall_port',
            constraint=models.UniqueConstraint(fields=('office', 'wall_port'), name='unique_office_wall_port'),
        ),
    ]
