from core.sh.forms.brands.forms import BrandForm
from core.sh.forms.connection_type.forms import ConnectionTypeForm
from core.sh.forms.dependency.forms import DependencyForm
from core.sh.forms.dev_model.forms import Dev_ModelForm
from core.sh.forms.dev_status.forms import Dev_StatusForm
from core.sh.forms.dev_type.forms import Dev_TypeForm
from core.sh.forms.edifice.forms import EdificeForm
from core.sh.forms.employee.forms import EmployeeForm
from core.sh.forms.employee_status.forms import EmployeeStatusForm
from core.sh.forms.location.forms import LocationForm
from core.sh.forms.move_type.forms import MoveTypeForm
from core.sh.forms.movements.forms import Movements
from core.sh.forms.office.forms import OfficeForm
from core.sh.forms.office_loc.forms import Office_Loc_Form
from core.sh.forms.patch_port.forms import PatchPortForm
from core.sh.forms.patchera.forms import PatcheraForm
from core.sh.forms.province.forms import ProvinceForm
from core.sh.forms.rack.forms import RackForm
from core.sh.forms.suply.forms import SuplyForm

from core.sh.forms.device.forms import DeviceForm
from core.sh.forms.switch.forms import SwitchForm