from ..models.brands.models import Brand
from ..models.connection_type.models import Connection_Type
from ..models.dependency.models import Dependency
from ..models.dev_model.models import Dev_Model
from ..models.dev_status.models import Dev_Status
from ..models.dev_type.models import Dev_Type
from ..models.device.models import Device
from ..models.edifice.models import Edifice
from ..models.employee.models import Employee
from ..models.employee_status.models import Employee_Status
from ..models.location.models import Location
from ..models.move_type.models import Move_Type
from ..models.movements.models import Movements
from ..models.office.models import Office
from ..models.office_loc.models import Office_Loc
from ..models.patch_port.models import Patch_Port
from ..models.patchera.models import Patchera
from ..models.province.models import Province
from ..models.rack.models import Rack
from ..models.suply.models import Suply
from ..models.suply_type.models import Suply_Type
from ..models.switch.models import Switch
from ..models.switch_port.models import Switch_Port
from ..models.tehcs.models import Techs
from ..models.wall_port.models import Wall_Port